# Concatenate migration SQL files (correct order) into one file for Supabase SQL Editor.
# Large scripts may hit editor limits — prefer: .\scripts\run-all-migrations.ps1
#
# Usage:
#   .\scripts\combine-migrations.ps1
# Output: all-migrations-combined.sql in repo root (gitignored pattern: add to .gitignore if needed)

$ErrorActionPreference = "Stop"
$root = Join-Path $PSScriptRoot ".."
$migrations = Join-Path $root "migrations"
$outPath = Join-Path $root "all-migrations-combined.sql"

$order = @(
    "create_clients_tables.sql",
    "create_consult_tables.sql",
    "create_booking_tables.sql",
    "add_address_fields_to_clients.sql",
    "add_first_last_name_to_clients.sql",
    "add_formula_data_column.sql",
    "add_buffer_time_to_clinic_settings.sql",
    "add_currency_to_clinic_settings.sql",
    "add_profile_fields.sql",
    "add_onboarding_and_practice_address.sql",
    "fix_profiles_rls_self_access.sql",
    "add_missing_indexes.sql"
)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("-- Combined migrations for Supabase SQL Editor")
[void]$sb.AppendLine("-- Generated by scripts/combine-migrations.ps1 — review before run.")
[void]$sb.AppendLine()

foreach ($name in $order) {
    $f = Join-Path $migrations $name
    if (-not (Test-Path $f)) { throw "Missing file: $f" }
    [void]$sb.AppendLine("-- ========== $name ==========")
    [void]$sb.AppendLine((Get-Content -Path $f -Raw -Encoding UTF8))
    [void]$sb.AppendLine()
}

[System.IO.File]::WriteAllText($outPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $outPath"
Write-Host "Open Supabase → SQL → New query → paste file contents (or upload)."
